CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  verified INTEGER DEFAULT 0,   -- 0 = not verified, 1 = verified
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
