services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-P", "3306", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - .data/mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh entrypoint.sh
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      DB_HOST: mysql   # Ensure DB_HOST is set to 'mysql' for the PHP server to connect to MySQL
      DB_PORT: 3306
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
